- src/core/public/application/types.ts
- src/core/public/index.ts
- src/core/types/index.ts
- src/core/types/workspace_template.ts
- src/core/utils/default_workspace_templates.ts
- src/core/utils/index.ts
- src/plugins/dashboard/public/plugin.tsx
- src/plugins/workspace/public/hooks.ts
workspace template register and consume
> workspace template init commit

- src/core/public/application/types.ts
- src/core/public/core_system.ts
- src/core/public/index.ts
- src/core/public/plugins/plugin_context.ts
- src/core/public/workspace/index.ts
- src/core/public/workspace/workspaces_client.ts
- src/core/public/workspace/workspaces_service.ts
> Add interfaces and partial implement for public core.workspaces

- src/core/public/chrome/chrome_service.tsx
- src/core/public/chrome/ui/header/collapsible_nav.tsx
- src/core/public/chrome/ui/header/header.tsx
- src/core/public/core_system.ts
- src/core/server/dev/dev_config.ts
init workspace menu stage 1.  features is an array of string, will specific and wait real data to do integration
> init workspace menu stage 1

- src/plugins/workspace/common/constants.ts
- src/plugins/workspace/public/components/routes.ts
- src/plugins/workspace/public/components/workspace_overview.tsx
- src/plugins/workspace/public/plugin.ts
> Add workspace overview page

- src/core/server/workspaces/routes/index.ts
- src/core/server/workspaces/saved_objects/workspace.ts
- src/core/server/workspaces/types.ts
- src/plugins/workspace/public/components/workspace_creator/workspace_form.tsx
- src/plugins/workspace/public/components/workspace_creator/workspace_icon_selector.tsx
Add color, icon and defaultVISTheme for workspace
> Add color, icon and defaultVISTheme for workspace

- src/core/public/chrome/chrome_service.tsx
- src/core/public/chrome/constants.ts
- src/core/public/chrome/ui/header/collapsible_nav.test.tsx
- src/core/public/chrome/ui/header/collapsible_nav.tsx
- src/core/public/chrome/ui/header/header.test.tsx
- src/core/public/chrome/ui/header/header.tsx
- src/core/public/chrome/ui/header/nav_link.tsx
- src/plugins/workspace/public/components/workspace_app.tsx
- src/plugins/workspace/public/plugin.ts
1. Different left menu when inside and outside workspace. (See screenshots below)
2. Enable users to exit workspace through "Exit workspace" button on the left menu.
3. Implement a dropdown list for workspaces when outside workspaces. Users can enter workspace by clicking the workspace shown in the list. If there are more than 5 workspaces, only show the first 5 of them.
4. For outside workspace menu, implement "Home" button directing to OpenSearch Dashboards homepage.
5. For outside workspace menu, implement "SEE MORE" directing to workspace lists page.
6. For inside workspace menu, implement "Overview" button directing workspace update page.
Outside workspace:
Inside workspace:
> feat: different left menu and exit workspace

- src/core/public/http/base_path.ts
- src/core/public/http/http_service.ts
- src/core/public/http/types.ts
- src/core/public/injected_metadata/injected_metadata_service.ts
- src/plugins/workspace/public/plugin.ts
> feat: optimize code for stateful url

- src/core/server/workspaces/index.ts
- src/core/server/workspaces/workspace_permission_control.ts
- src/core/server/workspaces/workspaces_service.ts
Add workspace permission control interface
> feat: add workspace permission control interface

- src/core/public/chrome/chrome_service.tsx
- src/core/public/core_app/core_app.ts
- src/core/public/core_system.ts
- src/core/public/http/types.ts
- src/core/public/ui_settings/ui_settings_service.mock.ts
- src/core/public/workspace/workspaces_client.ts
- src/core/public/workspace/workspaces_service.ts
- src/core/server/server.ts
- src/core/server/ui_settings/settings/index.test.ts
- src/core/server/ui_settings/settings/index.ts
- src/core/server/ui_settings/settings/workspace.ts
- src/core/server/workspaces/workspaces_service.ts
- src/plugins/workspace/public/containers/workspace_dropdown_list/workspace_dropdown_list.tsx
- src/plugins/workspace/public/mount.tsx
- src/plugins/workspace/public/plugin.ts
This PR adds a `workspace` configuration section in advance settings which allows user to turn on/off workspace feature.
None
> allow user to turn on/off workspace from advance settings

- src/core/public/workspace/workspaces_client.ts
- src/core/server/saved_objects/service/lib/repository.ts
- src/core/server/saved_objects/service/saved_objects_client.ts
- src/core/server/workspaces/saved_objects/index.ts
- src/core/server/workspaces/saved_objects/workspace_saved_objects_client_wrapper.ts
- src/core/server/workspaces/workspace_permission_control.ts
- src/core/server/workspaces/workspaces_service.ts
Add workspace saved objects client wrapper.
> add workspace saved objects client wrapper

- src/core/public/application/types.ts
- src/plugins/workspace/public/components/utils/feature.test.ts
- src/plugins/workspace/public/components/utils/feature.ts
- src/plugins/workspace/public/components/workspace_creator/workspace_form.tsx
1. filter out ADMIN application in workspace form
2. add feature dependencies logic
> feat: filter out ADMIN application and add feature dependency logic

- src/core/server/workspaces/saved_objects/workspace_saved_objects_client_wrapper.ts
Apply workspace permission check when saving object
> Apply workspace permission check when saving object 

- src/core/public/chrome/nav_links/nav_links_service.ts
- src/plugins/workspace/public/plugin.ts
Refactor the default value setting from workspace plugin.ts to nav_link_service.ts. Specifically, if `filteredNavLinks` is not empty, we can directly return it. Otherwise, we return the default value `navLinks`.
> Refactor: Assign default value for filtered nav links

- src/core/server/server.ts
- src/core/server/workspaces/workspaces_service.ts
Removed server side check of workspace feature flag
> Remove server side workspace feature flag check

- src/core/server/workspaces/saved_objects/workspace_saved_objects_client_wrapper.ts
apply workspace permission check when bulk creating object
> apply workspace permission check when bulk creating object

- src/core/public/saved_objects/saved_objects_client.ts
- src/core/server/saved_objects/permission_control/acl.test.ts
- src/core/server/saved_objects/permission_control/acl.ts
- src/core/server/saved_objects/permission_control/client.mock.ts
- src/core/server/saved_objects/permission_control/client.ts
- src/core/server/saved_objects/permission_control/routes/principles.ts
- src/core/server/saved_objects/saved_objects_service.ts
- src/core/server/saved_objects/serialization/types.ts
- src/core/server/saved_objects/service/lib/repository.ts
- src/core/server/saved_objects/service/lib/search_dsl/query_params.ts
- src/core/server/saved_objects/service/lib/search_dsl/search_dsl.ts
- src/core/server/saved_objects/types.ts
- src/core/server/workspaces/saved_objects/workspace_saved_objects_client_wrapper.ts
- src/core/types/saved_objects.ts
1. Make saved objects search under ACL DSL control.
2. Implement permission_service.
> Integration ACL check with saved objects.

- src/core/public/workspace/workspaces_client.ts
- src/core/server/saved_objects/serialization/serializer.ts
- src/core/server/saved_objects/serialization/types.ts
- src/core/server/saved_objects/service/lib/repository.ts
- src/core/server/saved_objects/service/saved_objects_client.ts
- src/core/server/workspaces/index.ts
- src/core/server/workspaces/types.ts
- src/core/server/workspaces/workspaces_client.ts
Move permissions attribute outside instead on in workspace attributes
> write permisions outside instead of workspace attributes

- src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
add permission check when updating workspace
>  add permission check when updating workspace

- src/core/public/workspace/workspaces_service.ts
- src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
A navigation bug for delete and exit workspace has been fixed in this PR. With this PR, the user will only navigation to home page when delete and exit workspace successfully. Also, I also fixed a bug for workspace start. The value of `workspaceEnabled$` will unsubscribe when `WorkspaceService` get stopped.
The error message remains the same:
> fix: redirect to home only when delete and exit workspace successfully

- src/core/server/http/index.ts
- src/core/server/index.ts
- src/plugins/workspace/server/routes/index.ts
Add management permission by default to workspace creator
> feat: add management permission for workspace create user

- src/core/public/chrome/nav_links/nav_link.ts
- src/core/public/chrome/ui/header/collapsible_nav.tsx
- src/core/public/chrome/ui/header/nav_link.tsx
The category name has changed from "recently viewed" to "recently visited". We need to confirm with UX team whether to render this category when there is no recently accessed items.
> refactor: in left menu, move recently viewed from top to middle

- config/opensearch_dashboards.yml
- src/plugins/workspace/config.ts
- src/plugins/workspace/server/index.ts
- src/plugins/workspace/server/plugin.ts
- src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
> feat: accomplish dashboard_admin

- src/plugins/saved_objects_management/public/constants.ts
- src/plugins/saved_objects_management/public/plugin.ts
This PR renames the second **Overview** in library category to **All library objects** and changes title from **Saved Objects** to **Library objects in Analytics**
> fix: two "Overview"s under library section

- src/core/server/saved_objects/permission_control/client.ts
- src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
add workspace attribute check and refactor saved object acl check
> add workspace attribute check and refactor saved object acl check

- src/core/public/chrome/nav_links/nav_links_service.ts
- src/core/public/chrome/ui/header/collapsible_nav.tsx
- src/core/public/chrome/ui/header/collapsible_nav_header.tsx
- src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
- src/plugins/workspace/public/plugin.ts
- src/plugins/workspace/server/plugin.ts
> feat: filter applications according to categories

- src/plugins/workspace/config.ts
- src/plugins/workspace/public/plugin.ts
- src/plugins/workspace/public/workspace_client.ts
- src/plugins/workspace/server/plugin.ts
- src/plugins/workspace/server/routes/index.ts
- src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
> [Refractor] Feature flag

- src/plugins/workspace/config.ts
- src/plugins/workspace/public/plugin.ts
- src/plugins/workspace/public/workspace_client.ts
- src/plugins/workspace/server/plugin.ts
- src/plugins/workspace/server/routes/index.ts
This reverts commit e2f277c1b48b41a05e1ee447430a26f64fcab432.
> Revert "[Refractor] Feature flag (#102)"

- src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
- src/core/public/saved_objects/saved_objects_client.ts
- src/core/server/saved_objects/permission_control/client.ts
- src/core/server/saved_objects/service/lib/repository.mock.ts
- src/core/server/saved_objects/service/lib/repository.ts
- src/core/server/saved_objects/service/lib/search_dsl/query_params.ts
- src/core/server/saved_objects/service/lib/search_dsl/search_dsl.ts
- src/core/server/saved_objects/service/lib/utils.ts
- src/core/server/saved_objects/service/saved_objects_client.ts
- src/core/server/saved_objects/types.ts
- src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
> Refractor: remove `processFindOptions` and `getPermissionQuery` methods declaration in repositoryClient

- src/core/server/saved_objects/routes/index.ts
- src/core/server/saved_objects/routes/share.ts
- src/core/server/saved_objects/service/lib/repository.ts
- src/core/server/saved_objects/service/saved_objects_client.ts
> Remove public workspace logic for share API

- src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
- src/core/public/saved_objects/saved_objects_client.ts
- src/core/server/saved_objects/permission_control/client.ts
- src/core/server/saved_objects/service/lib/repository.mock.ts
- src/core/server/saved_objects/service/lib/repository.ts
- src/core/server/saved_objects/service/lib/search_dsl/query_params.ts
- src/core/server/saved_objects/service/lib/search_dsl/search_dsl.ts
- src/core/server/saved_objects/service/lib/utils.ts
- src/core/server/saved_objects/service/saved_objects_client.ts
- src/core/server/saved_objects/types.ts
- src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
…ds declaration in repositoryClient (#142)
* refractor: remove additional method declaration
Signed-off-by: SuZhou-Joe <suzhou@amazon.com>
* feat: make bootstrap run
Signed-off-by: SuZhou-Joe <suzhou@amazon.com>
* feat: change to single permission modes
Signed-off-by: SuZhou-Joe <suzhou@amazon.com>
* feat: rename variable
Signed-off-by: SuZhou-Joe <suzhou@amazon.com>
---------
Signed-off-by: SuZhou-Joe <suzhou@amazon.com>
(cherry picked from commit 05fab00a1e9f90ccfae754bd4073c3fa4954b774)
> [Backport workspace-2.9]Refractor: remove `processFindOptions` and `getPermissionQuery` methods declaration in repositoryClient (#142)

- src/core/server/saved_objects/migrations/core/__snapshots__/build_active_mappings.test.ts.snap
- src/core/server/saved_objects/migrations/core/build_active_mappings.ts
- src/core/server/saved_objects/migrations/core/index_migrator.test.ts
- src/core/server/saved_objects/migrations/opensearch_dashboards/__snapshots__/opensearch_dashboards_migrator.test.ts.snap
- src/core/server/saved_objects/permission_control/acl.test.ts
- src/core/server/saved_objects/permission_control/acl.ts
The main change of this PR are:
1. Add acl related functions for workspace feature
2. Add permissions field to the default mapping of the OSD index(.kibana)
3. Update the test snapshot after we change the default mapping of the OSD index
> [Workspace] Add ACL related functions for workspace

- .github/workflows/build_and_test_workflow.yml
- .github/workflows/cypress_workflow.yml
the jobs for windows are queued forever, disable it for development
> disable github workflows running on windows for development

- src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
> fix: update unit test snapshot for header

- src/core/server/index.ts
- src/core/server/legacy/legacy_service.ts
- src/core/server/plugins/plugin_context.ts
- src/core/server/saved_objects/index.ts
- src/core/server/saved_objects/saved_objects_service.mock.ts
- src/core/server/saved_objects/saved_objects_service.ts
- src/plugins/workspace/server/permission_control/client.mock.ts
- src/plugins/workspace/server/permission_control/client.ts
- src/plugins/workspace/server/permission_control/routes/index.ts
- src/plugins/workspace/server/permission_control/routes/principals.ts
- src/plugins/workspace/server/permission_control/routes/validate.ts
- src/plugins/workspace/server/plugin.ts
- src/plugins/workspace/server/routes/index.ts
> Refractor: move permission control service to workspace directory and keep saved objects as clean as possible

- src/core/server/index.ts
- src/core/server/legacy/legacy_service.ts
- src/core/server/plugins/plugin_context.ts
- src/core/server/saved_objects/index.ts
- src/core/server/saved_objects/saved_objects_service.mock.ts
- src/core/server/saved_objects/saved_objects_service.ts
- src/plugins/workspace/server/permission_control/client.mock.ts
- src/plugins/workspace/server/permission_control/client.ts
- src/plugins/workspace/server/permission_control/routes/index.ts
- src/plugins/workspace/server/permission_control/routes/principals.ts
- src/plugins/workspace/server/permission_control/routes/validate.ts
- src/plugins/workspace/server/plugin.ts
- src/plugins/workspace/server/routes/index.ts
* refractor: move permission control service to workspace directory and keep saved objects as clean as possible
Signed-off-by: SuZhou-Joe <suzhou@amazon.com>
* feat: make lint pass
Signed-off-by: SuZhou-Joe <suzhou@amazon.com>
---------
Signed-off-by: SuZhou-Joe <suzhou@amazon.com>
(cherry picked from commit c2a9bd24acba983353f43db80ec98f54ba7e15c3)
> [Backport workspace-2.9]Refractor: move permission control service to workspace directory and keep saved objects as clean as possible (#166)

- src/plugins/advanced_settings/public/plugin.ts
- src/plugins/opensearch_dashboards_react/public/overview_page/overview_page_header/overview_page_header.tsx
- src/plugins/saved_objects_management/public/plugin.ts
- src/plugins/workspace/public/plugin.ts
* feat: retire management section
Signed-off-by: tygao <tygao@amazon.com>
* fix: fix path
Signed-off-by: tygao <tygao@amazon.com>
* chore: remove unused
Signed-off-by: tygao <tygao@amazon.com>
* fix: update path
Signed-off-by: tygao <tygao@amazon.com>
* fix: update path
Signed-off-by: tygao <tygao@amazon.com>
* chore: remove unused after rebase
Signed-off-by: tygao <tygao@amazon.com>
* fix: remove extra import
Signed-off-by: tygao <tygao@amazon.com>
---------
Signed-off-by: tygao <tygao@amazon.com>
(cherry picked from commit d7dbedf2848204c7ad615d26f2865d49db147143)
> [manually backport workspace-2.9] Retire dashboards management (#138)

- src/plugins/workspace/server/permission_control/client.ts
- src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
- src/plugins/workspace/server/workspace_client.ts
1. use passed ACLSearchParams.permissionModes
2. move getPermittedWorkspaceIds to find method
3. remove permissionModes parameter, use `ACLSearchParams.permissionModes` instead
> feat: use passed ACLSearchParams.permissionModes

- .github/workflows/build_and_test_workflow.yml
- .github/workflows/cypress_workflow.yml
Use self hosted runner and disable windows workflow + use forked functional-test repo for development
> use self hosted runner and disable windows workflow

- src/plugins/data/public/search/errors/painless_error.tsx
- src/plugins/opensearch_dashboards_react/public/overview_page/overview_page_header/overview_page_header.test.tsx
1. Fix failed UT for retire dashboards management
2. Fix missed index pattern path change
> Fix failed UT for index pattern and retire dashboard management

- src/plugins/workspace/server/permission_control/client.ts
- src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
- src/plugins/workspace/server/workspace_client.ts
* feat: workspace saved client wrapper ACLSearchParams.permissionModes use passed value
Signed-off-by: Lin Wang <wonglam@amazon.com>
* refactor: move getPermittedWorkspaceIds inner find method
Signed-off-by: Lin Wang <wonglam@amazon.com>
* feat: remove permissionModes in savedobject client find method
Signed-off-by: Lin Wang <wonglam@amazon.com>
---------
Signed-off-by: Lin Wang <wonglam@amazon.com>
(cherry picked from commit 33e90ec92c93653ac17c72e2348c1f32ba53661c)
Manual backport #181 to workspace 2.9
> [Backport workspace-2.9] feat: use passed ACLSearchParams.permissionModes (#181)

- src/core/public/core_system.test.mocks.ts
- src/core/public/core_system.test.ts
- src/core/public/core_system.ts
- src/core/public/mocks.ts
- src/core/public/plugins/plugins_service.test.ts
- src/core/public/workspace/workspaces_service.mock.ts
- src/core/public/workspace/workspaces_service.test.ts
- src/core/public/workspace/workspaces_service.ts
Added unit tests for core `WorkspacesService`
> Test for workspace core service

- src/core/public/application/types.ts
- src/core/public/chrome/chrome_service.tsx
- src/core/public/chrome/ui/header/collapsible_nav.tsx
- src/core/public/chrome/ui/header/collapsible_nav_header.tsx
- src/core/public/chrome/ui/header/header.tsx
- src/core/public/core_system.test.mocks.ts
- src/core/public/core_system.test.ts
- src/core/public/core_system.ts
- src/core/public/index.ts
- src/core/public/mocks.ts
- src/core/public/plugins/plugins_service.test.ts
- src/core/public/workspace/index.ts
- src/core/public/workspace/workspaces_service.mock.ts
- src/core/public/workspace/workspaces_service.test.ts
- src/core/public/workspace/workspaces_service.ts
- src/plugins/home/public/application/opensearch_dashboards_services.ts
- src/plugins/saved_objects_management/public/management_section/objects_table/components/duplicate_modal.tsx
- src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.tsx
- src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
- src/plugins/workspace/public/workspace_client.ts
+ workspace integration branch pr patch which includes:
1. WorkspaceService unit test
2. Some renames
> add unit tests for workspace core service (#191)

- src/plugins/workspace/public/components/workspace_creator/workspace_form.tsx
- src/plugins/workspace/server/routes/index.ts
- src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
1. In workspace update page, support to display workspace feature configured with wildcard.
2. Fixed an issue which generateWorkspacePermissionError return void
3. Fixed an issue which workspace route validation failed due to missing permission mode in schema
4. Hide feature configure panel for management workspace
> Support to display workspace feature configured with wildcard

- src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
- src/plugins/workspace/server/routes/index.ts
- src/plugins/workspace/server/workspace_client.ts
1. Hide delete button for **reserved** workspace in **workspace update** page
2. For **update workspace** API, **reserved** workspace name cannot be changes
> feat: reserved workspace customization

- src/core/utils/constants.ts
- src/plugins/workspace/public/components/workspace_creator/workspace_permission_setting_panel.tsx
- src/plugins/workspace/public/workspace_client.ts
- src/plugins/workspace/server/routes/index.ts
- src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
- src/plugins/workspace/server/types.ts
1.Remove management permission mode
2.Update workspaces permission check use LibraryRead / LibraryWrite
3.Update ACL permission check use Read / Write
4.Change workspace permission form use below options
- Read: LibraryRead + Read
- Read+Write: LibraryWrite + Write
- Admin: LibraryWrite + Write
> Feat remove management permission mode in acl permission

- src/core/public/core_system.test.ts
- src/core/public/core_system.ts
- src/core/public/workspace/workspaces_service.mock.ts
- src/core/public/workspace/workspaces_service.test.ts
- src/core/public/workspace/workspaces_service.ts
- src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
- src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
@SuZhou-Joe had a good suggestion to move the workspace menu render from core workspace service module to chrome service, this PR is about to remove it from core workspace service
> remove unnecessary workspace menu register

- src/core/server/index.ts
- src/core/server/saved_objects/routes/integration_tests/share.test.ts
- src/core/server/saved_objects/routes/share.ts
- src/core/server/saved_objects/routes/utils.test.ts
- src/core/server/saved_objects/routes/utils.ts
- src/core/server/saved_objects/service/lib/repository.test.js
- src/core/server/saved_objects/service/lib/repository.ts
- src/core/server/saved_objects/service/saved_objects_client.mock.ts
- src/core/server/saved_objects/service/saved_objects_client.ts
1. make addToWorkspaceOptions extends SavedObjectsBaseOptions
2. Add unit test
> Add more unit test for share/delete api 

- CHANGELOG.md
- src/plugins/workspace/server/integration_tests/routes.test.ts
- src/plugins/workspace/server/routes/index.ts
- src/plugins/workspace/server/types.ts
- test/api_integration/apis/index.js
- test/api_integration/apis/workspace/index.ts
* temp: add unit test
* feat: add function test for workspace CRUD routes
* feat: use saved objects client instead of internal repository
* feat: update CHANGELOG
* feat: exclude permission check wrapper
* feat: add integration test
* feat: add configuration
* feat: enable workspace flag when run workspace related test
---------
> [Backport workspace]Patch/first pr (#194)

- src/core/server/saved_objects/service/lib/search_dsl/query_params.ts
- src/plugins/workspace/server/saved_objects/integration_tests/workspace_saved_objects_client_wrapper.test.ts
- src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
1. Fix permission validate for `addToWorkspaces` and `deleteByWorkspace` in client wrapper
2. Add integration tests for workspace saved object client wrapper
> Add integration test for workspace saved objects client wrapper

- src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
add permission check for bulkCreate when overwrite
>  add permission check for bulkCreate when overwrite

- src/core/public/application/capabilities/capabilities_service.mock.ts
- src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
- src/core/public/index.ts
- src/core/public/workspace/index.ts
- src/core/public/workspace/workspaces_service.mock.ts
- src/core/public/workspace/workspaces_service.test.ts
- src/core/public/workspace/workspaces_service.ts
- src/core/server/capabilities/capabilities_service.mock.ts
- src/core/server/capabilities/capabilities_service.test.ts
- src/core/server/capabilities/capabilities_service.ts
- src/core/server/capabilities/integration_tests/capabilities_service.test.ts
- src/core/server/capabilities/resolve_capabilities.test.ts
- src/core/types/capabilities.ts
- src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
- src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
Removed `workspaceEnabled$` from workspace service module, a followup PR will create to implement the flag within capabilities service
> Core module pr patch

- src/plugins/workspace/server/permission_control/client.ts
- src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
1. Add in memory validate in permission control
2. Use in memory validate for object ACL validate
> feat: remove unnecessary saved object get call

- src/plugins/saved_objects_management/public/plugin.test.ts
> feat: add unit test for mountWrapper

- src/plugins/workspace/server/saved_objects/integration_tests/workspace_saved_objects_client_wrapper.test.ts
- src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
Fix create and bulkCreate can't override with permitted target workspaces
> fix: create and bulkCreate override with target workspaces

- src/core/public/chrome/chrome_service.tsx
- src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
- src/plugins/workspace/public/render_workspace_menu.tsx
currently, navigate to "Create workspace" page and "All workspace" list page from workspace context menu triggers a full page reload which is unnecessary.
> navigate to create workspace/workspaces list page without refreshing

- src/core/server/index.ts
- src/core/server/saved_objects/service/lib/repository.mock.ts
- src/core/server/saved_objects/service/lib/repository.test.js
- src/core/server/saved_objects/service/lib/repository.ts
- src/core/server/saved_objects/service/saved_objects_client.test.js
- src/core/server/saved_objects/service/saved_objects_client.ts
- src/plugins/workspace/server/integration_tests/routes.test.ts
- src/plugins/workspace/server/routes/index.ts
- src/plugins/workspace/server/workspace_client.ts
1. Delete saved objects by workspace
> [API] Delete saved objects by workspace

- src/plugins/home/public/application/components/sample_data_set_cards.js
- src/plugins/home/public/application/opensearch_dashboards_services.ts
- src/plugins/home/public/application/sample_data_client.js
- src/plugins/home/public/plugin.ts
- src/plugins/home/server/services/sample_data/data_sets/ecommerce/index.ts
- src/plugins/home/server/services/sample_data/data_sets/flights/index.ts
- src/plugins/home/server/services/sample_data/data_sets/logs/index.ts
- src/plugins/home/server/services/sample_data/data_sets/util.ts
- src/plugins/home/server/services/sample_data/lib/sample_dataset_registry_types.ts
- src/plugins/home/server/services/sample_data/routes/install.test.ts
- src/plugins/home/server/services/sample_data/routes/install.ts
- src/plugins/home/server/services/sample_data/routes/list.test.ts
- src/plugins/home/server/services/sample_data/routes/list.ts
- src/plugins/home/server/services/sample_data/routes/uninstall.test.ts
- src/plugins/home/server/services/sample_data/routes/uninstall.ts
Import sample data to specific workspace
> [Workspace][Feature]  Import sample data to workspace

- config/opensearch_dashboards.yml
- src/plugins/workspace/config.ts
- src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
- src/plugins/workspace/public/components/workspace_creator/workspace_form.tsx
- src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
- src/plugins/workspace/server/integration_tests/routes.test.ts
- src/plugins/workspace/server/plugin.ts
When OSD don't have authentication enabled, there is no user/role. In this case, permission check for workspace need to be disabled, otherwise it will block the access to saved objects belongs to workspaces.
To support this we could check whether authentication has configured, but it lose the flexibility to turn on/off based on user's need.
By adding a new flag in yml file, it is more flexible, user could turn permission check off even if authentication is enabled.
**This flag will skip permission check totally. However, for creating/updating workspace, it will still persistent the ACL related information, that info could be reuse when permission check turned on.**
> Support disable permission check on workspace

- src/core/server/saved_objects/service/lib/repository.ts
- src/core/server/saved_objects/service/saved_objects_client.test.js
- src/plugins/workspace/server/integration_tests/routes.test.ts
- src/plugins/workspace/server/workspace_client.ts
Backport delete saved objects by workspace unit test cases into workspace branch
> [Backport workspace]Add unit test for delete saved objects by workspace

- src/plugins/workspace/common/constants.ts
- src/plugins/workspace/public/components/workspace_creator/workspace_bottom_bar.tsx
- src/plugins/workspace/public/components/workspace_creator/workspace_cancel_modal.tsx
- src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
- src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
- src/plugins/workspace/public/components/workspace_creator/workspace_form.tsx
- src/plugins/workspace/public/components/workspace_creator/workspace_icon_selector.tsx
- src/plugins/workspace/public/components/workspace_creator/workspace_permission_setting_panel.tsx
- src/plugins/workspace/public/components/workspace_creator_app.tsx
- src/plugins/workspace/public/components/workspace_list_app.tsx
- src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
- src/plugins/workspace/public/plugin.ts
1. Update create workspace page UI
2. Implement unit tests
> feat: update create workspace page UI and implement unit tests

- src/core/server/saved_objects/routes/copy.ts
- src/core/server/saved_objects/routes/index.ts
- src/core/server/saved_objects/routes/integration_tests/copy.test.ts
Add copy saved objects API and add some integration tests.
> Add copy saved objects API

- src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
- src/plugins/workspace/public/components/workspace_creator/workspace_form.tsx
- src/plugins/workspace/public/components/workspace_creator/workspace_permission_setting_panel.tsx
In workspace update page, users cannot delete the last user or group with admin permission.
> feature: cannot delete last admin user/group in workspace settings

- src/core/server/index.ts
- src/core/utils/constants.ts
- src/core/utils/index.ts
- src/plugins/console/public/application/components/import_flyout.test.tsx
- src/plugins/workspace/common/constants.ts
- src/plugins/workspace/server/integration_tests/routes.test.ts
- src/plugins/workspace/server/plugin.ts
- src/plugins/workspace/server/workspace_client.ts
> Feature: create management / public workspaces when calling list api

- src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
- src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
- src/plugins/workspace/public/components/workspace_creator/workspace_form.tsx
- src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
- src/plugins/workspace/public/workspace_client.ts
- src/plugins/workspace/server/routes/index.ts
- src/plugins/workspace/server/types.ts
- src/plugins/workspace/server/workspace_client.ts
1. Move permissions out of attributes parameter
2. Disable duplicate permission for specific user or group
> Feat disable duplicate user or group permission

- src/core/public/saved_objects/saved_objects_client.ts
- src/core/server/saved_objects/service/lib/repository.ts
- src/core/server/saved_objects/service/lib/search_dsl/query_params.test.ts
- src/core/server/saved_objects/service/lib/search_dsl/query_params.ts
- src/core/server/saved_objects/service/lib/search_dsl/search_dsl.ts
- src/core/server/saved_objects/types.ts
- src/plugins/workspace/server/workspace_client.ts
Add an new option `flag` for find method which is used for simple query string limit operators.
with `flags` as `NONE`, all reserved keyword for simple query string will treated as literal string.
> Add simple string query flags options to find method

- src/plugins/workspace/public/workspace_client.ts
- src/plugins/workspace/server/integration_tests/routes.test.ts
- src/plugins/workspace/server/routes/index.ts
> fix: permissions missed after workspace update

- src/plugins/workspace/server/permission_control/client.ts
- src/plugins/workspace/server/plugin.ts
- src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
Regarding PR https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5075, we will make workspace as a hidden type so that it won't be modified by normal saved objects client. So that we'd have to include workspace as hidden types of saved objects wrapper and saved objects permission control service.
> feat: add workspace into includeHiddenTypes

- src/plugins/workspace/server/integration_tests/routes.test.ts
> fix: workspace routes integration failed

- src/plugins/workspace/server/saved_objects/integration_tests/workspace_saved_objects_client_wrapper.test.ts
- src/plugins/workspace/server/workspace_client.ts
> Fix existing failed integration test cases

- CHANGELOG.md
- config/opensearch_dashboards.yml
- src/core/server/saved_objects/import/create_saved_objects.ts
- src/core/server/saved_objects/import/import_saved_objects.ts
- src/core/server/saved_objects/import/resolve_import_errors.ts
- src/core/server/saved_objects/import/types.ts
- src/core/server/saved_objects/migrations/core/__snapshots__/build_active_mappings.test.ts.snap
- src/core/server/saved_objects/migrations/core/build_active_mappings.test.ts
- src/core/server/saved_objects/migrations/core/build_active_mappings.ts
- src/core/server/saved_objects/migrations/core/index_migrator.test.ts
- src/core/server/saved_objects/migrations/core/migration_context.ts
- src/core/server/saved_objects/migrations/opensearch_dashboards/__snapshots__/opensearch_dashboards_migrator.test.ts.snap
- src/core/server/saved_objects/migrations/opensearch_dashboards/opensearch_dashboards_migrator.test.ts
- src/core/server/saved_objects/migrations/opensearch_dashboards/opensearch_dashboards_migrator.ts
- src/core/server/saved_objects/routes/import.ts
- src/core/server/saved_objects/routes/resolve_import_errors.ts
- src/core/server/saved_objects/saved_objects_service.ts
- src/core/server/saved_objects/service/saved_objects_client.ts
- src/plugins/workspace/server/saved_objects/integration_tests/saved_objects_wrapper_for_check_workspace_conflict.test.ts
- src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.test.ts
- src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.ts
> feat: cherry-pick pr #5949

- src/core/public/index.ts
- src/core/public/utils/index.ts
- src/core/server/index.ts
- src/core/utils/constants.ts
- src/core/utils/index.ts
- src/plugins/workspace/public/components/workspace_creator/workspace_form.tsx
- src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
- src/plugins/workspace/server/integration_tests/routes.test.ts
- src/plugins/workspace/server/workspace_client.ts
> remove management workspace

- src/core/public/index.ts
- src/core/public/mocks.ts
- src/core/public/utils/index.ts
- src/core/public/workspace/workspaces_service.mock.ts
- src/plugins/workspace/common/constants.ts
- src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx
- src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
- src/plugins/workspace/public/plugin.test.ts
- src/plugins/workspace/public/plugin.ts
- src/plugins/workspace/public/render_workspace_menu.tsx
In this commit, the workspace plugin registered a workspace dropdown menu on the top of left navigation bar. This allows user to quickly switch the current workspace.
> Add a workspace dropdown menu in left navigation bar

- src/core/public/index.ts
- src/core/server/index.ts
- src/core/utils/constants.ts
- src/core/utils/index.ts
- src/plugins/saved_objects_management/public/lib/get_saved_object_counts.ts
- src/plugins/saved_objects_management/public/lib/parse_query.test.ts
- src/plugins/saved_objects_management/public/lib/parse_query.ts
- src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
- src/plugins/saved_objects_management/public/management_section/objects_table/components/header.test.tsx
- src/plugins/saved_objects_management/public/management_section/objects_table/components/header.tsx
- src/plugins/saved_objects_management/public/management_section/objects_table/components/table.test.tsx
- src/plugins/saved_objects_management/public/management_section/objects_table/components/table.tsx
- src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.tsx
- src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
- src/plugins/saved_objects_management/server/routes/find.ts
- src/plugins/saved_objects_management/server/routes/scroll_count.ts
- src/plugins/workspace/opensearch_dashboards.json
- src/plugins/workspace/public/components/workspace_column/index.ts
- src/plugins/workspace/public/components/workspace_column/workspace_colum.test.tsx
- src/plugins/workspace/public/components/workspace_column/workspace_column.tsx
- src/plugins/workspace/public/plugin.test.ts
- src/plugins/workspace/public/plugin.ts
1. Add workspace filter into saved objects page
2. Add workspace column into saved objects page
**workspace column**
**workspace filter includes default workspace**
> Add workspace filter/column into saved objects page

- src/core/public/saved_objects/saved_objects_client.ts
* feat: consume current workspace in saved objects management and saved objects client
* feat: add unit test
* feat: add unit test for each change
* fix: update snapshot of unit test
* fix: unit test
* fix: unit test
* fix: unit test
* feat: update snapshot
* revert: saved object management changes
* feat: add CHANGELOG
* feat: address some comment
* feat: address comment
* feat: remove useless return
* fix: bootstrap error
* feat: update CHANGELOG
* feat: update CHANGELOG
* feat: optimize code
* feat: update comment
---------
> [Backport workspace-pr-integr][Workspace] Consume workspace id in saved object client (#6014)

- src/plugins/workspace/public/components/delete_workspace_modal/delete_workspace_modal.test.tsx
- src/plugins/workspace/public/components/workspace_list/index.test.tsx
fix failed modal cross component tests in ci env
> fix failed modal cross component tests in ci env

- src/core/public/chrome/ui/header/__snapshots__/collapsible_nav.test.tsx.snap
- src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
- src/core/public/http/base_path.test.ts
- src/core/public/http/base_path.ts
- src/core/public/http/http_service.mock.ts
- src/core/public/http/http_service.ts
- src/core/public/http/types.ts
- src/core/utils/workspace.test.ts
- src/core/utils/workspace.ts
- src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
- src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
- src/plugins/dashboard/public/application/embeddable/empty/__snapshots__/dashboard_empty_screen.test.tsx.snap
- src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
- src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/flyout.test.tsx.snap
- src/plugins/telemetry_management_section/public/components/__snapshots__/telemetry_management_section.test.tsx.snap
- src/plugins/workspace/public/components/delete_workspace_modal/delete_workspace_modal.tsx
- src/plugins/workspace/server/plugin.ts
> [Backport workspace-pr-integr] Add workspace id in base path

- CHANGELOG.md
- config/opensearch_dashboards.yml
- src/core/server/mocks.ts
- src/core/server/opensearch_dashboards_config.ts
- src/core/server/plugins/plugin_context.test.ts
- src/core/server/plugins/types.ts
- src/legacy/server/config/schema.js
- src/plugins/application_config/README.md
- src/plugins/application_config/common/index.ts
- src/plugins/application_config/config.ts
- src/plugins/application_config/opensearch_dashboards.json
- src/plugins/application_config/server/index.ts
- src/plugins/application_config/server/opensearch_config_client.test.ts
- src/plugins/application_config/server/opensearch_config_client.ts
- src/plugins/application_config/server/plugin.test.ts
- src/plugins/application_config/server/plugin.ts
- src/plugins/application_config/server/routes/index.test.ts
- src/plugins/application_config/server/routes/index.ts
- src/plugins/application_config/server/string_utils.test.ts
- src/plugins/application_config/server/string_utils.ts
- src/plugins/application_config/server/types.ts
* Add application configuration service
* update API path name
* implement two APIs/interfaces
* expose get function for other plugins to use
* update interfaces
* implement the APIs and interfaces
* add license and jsdoc
* update docs
* add more docs
* update variable name
* remove unnecessary dependency
* format readme
* use osd version
* remove debugging info
* update logging
* remove lint js
* remove logs
* update name style
* update
* update function visibility and error function
* fix unit test failures
* add unit test
* remove lint file
* add more tests
* add unit tests for routes
* add remaining unit tests
* add enabled to this plugin
* update readme to mention experimental
* update change log
* dummy commit to trigger workflow rerun
* remove experimental
* add key to yml file
* …
> [Backport workspace-pr-integr]Add support for dynamic application configurations (#5855)

- src/plugins/workspace/public/application.tsx
- src/plugins/workspace/public/components/workspace_form/workspace_bottom_bar.tsx
- src/plugins/workspace/public/components/workspace_updater/index.tsx
- src/plugins/workspace/public/components/workspace_updater/workspace_updater.test.tsx
- src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
- src/plugins/workspace/public/components/workspace_updater_app.tsx
- src/plugins/workspace/public/plugin.test.ts
- src/plugins/workspace/public/plugin.ts
Add update workspace page and add some unit test code.
> Add update workspace page

- src/plugins/workspace/public/workspace_client.test.ts
- src/plugins/workspace/public/workspace_client.ts
* feat: add comment
* feat: update unit test
* feat: add CHANGELOG
* feat: optimize comment
* feat: optimize comment
* feat: optimize code
* feat: optimize code
---------
> [Backport workspace-pr-integr][Workspace] Add a workspace client in workspace plugin (#6094)

- config/opensearch_dashboards.yml
- src/plugins/workspace/public/application.tsx
- src/plugins/workspace/public/components/workspace_overview/workspace_overview.tsx
- src/plugins/workspace/public/components/workspace_overview_app.tsx
- src/plugins/workspace/public/plugin.ts
> Workspace overview blank

- src/plugins/workspace/public/plugin.ts
- src/plugins/workspace/public/utils.test.ts
- src/plugins/workspace/public/utils.ts
> [Workspace] Filter left nav menu items according to the current workspace (#6234)

- src/plugins/application_config/server/opensearch_config_client.test.ts
- src/plugins/application_config/server/opensearch_config_client.ts
- src/plugins/application_config/server/plugin.test.ts
- src/plugins/application_config/server/plugin.ts
- src/plugins/application_config/server/types.ts
Improve dynamic configurations by adding cache and simplifying client fetch(#6364)
* Improve dynamic config
Signed-off-by: Tianle Huang <tianleh@amazon.com>
* reset yml
Signed-off-by: Tianle Huang <tianleh@amazon.com>
* bring back previous changes
Signed-off-by: Tianle Huang <tianleh@amazon.com>
> [backport]Improve dynamic configurations by adding cache and simplifying client fetch

- src/core/public/index.ts
- src/core/server/index.ts
- src/core/utils/constants.ts
- src/core/utils/index.ts
- src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.tsx
- src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
- src/plugins/saved_objects_management/server/routes/scroll_count.ts
- src/plugins/workspace/server/workspace_client.ts
Replace default workspace with public workspace, public workspace has parity with global tenant in 2.15.
> replace default workspace with public workspace

- src/core/server/saved_objects/routes/index.ts
- src/plugins/saved_objects/README.md
- src/plugins/workspace/README.md
- src/plugins/workspace/server/integration_tests/duplicate.test.ts
- src/plugins/workspace/server/integration_tests/routes.test.ts
- src/plugins/workspace/server/plugin.ts
- src/plugins/workspace/server/routes/duplicate.ts
- src/plugins/workspace/server/routes/index.ts
Backport the code change of OSD-core about duplicate API to this branch.
> [Backport] Add duplicate saved objects API (#6288)

- src/core/public/application/application_service.test.ts
- src/core/public/application/application_service.tsx
- src/core/public/application/index.ts
- src/core/public/application/integration_tests/application_service.test.tsx
- src/core/public/application/types.ts
- src/core/public/chrome/chrome_service.tsx
- src/core/public/chrome/nav_links/to_nav_link.test.ts
- src/core/public/chrome/nav_links/to_nav_link.ts
- src/core/public/core_system.ts
- src/core/public/index.ts
- src/plugins/home/public/plugin.ts
- src/plugins/opensearch_dashboards_overview/public/plugin.ts
- src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx
- src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
- src/plugins/workspace/public/plugin.ts
- src/plugins/workspace/public/utils.test.ts
- src/plugins/workspace/public/utils.ts
- src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.ts
Home page, which is supposed to be only visited without workspace, now is enabled to be accessed by clicking the home icon or enter the url manually in the browser.
This PR introduces a new field `AppVisibility` inside App, which indicates the visibility of the application. This field can bring two benefits:
1. When navigate between apps, plugins and core application are using the `navigateToApp` method. By using the visibility field, workspace is able to do the hard navigation in a central place.
2. The AppVisibility field can be used in workspace create page to filter applications that should not be visible inside workspace. For now we filter out home overview page and all the pages under management section by hard code, which is not elegant and extensible.
Extending the `status` field …
> [Workspace] Jump to non-workspace url when clicking home icon

- src/core/server/saved_objects/import/create_saved_objects.ts
- src/plugins/workspace/common/constants.ts
- src/plugins/workspace/server/plugin.ts
- src/plugins/workspace/server/saved_objects/integration_tests/workspace_id_consumer_wrapper.test.ts
- src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.ts
> [Backport workspace-pr-integr][Workspace] Support workspace in saved objects client in server side (#6365)

- src/core/public/saved_objects/saved_objects_client.ts
- src/core/server/saved_objects/service/lib/repository.ts
- src/core/server/saved_objects/service/lib/search_dsl/query_params.test.ts
- src/core/server/saved_objects/service/lib/search_dsl/query_params.ts
- src/core/server/saved_objects/service/lib/search_dsl/search_dsl.ts
- src/core/server/saved_objects/types.ts
- src/plugins/workspace/server/integration_tests/routes.test.ts
- src/plugins/workspace/server/workspace_client.ts
Add enabledOperators parameter for workspace name unique check. The default value for this flag is `ALL` means all operators are supported.
For example we have workspace named `test-workspace` and now we create a new workspace named `test test-workspace` that will match existing `test-workspace` by using simple query string and leads name unique check failed.
```
GET .kibana/_search
{
"query": {
"bool": {
"must": [
{
"term": {
"type": {
"value": "workspace"
}
}
},
{
"simple_query_string": {
"query": "test test-workspace", // this means match name by test or test-workspace
"fields": [
"workspace.name"
],
"flags": "ALL"
}
}
]
}
}
}
```
> Add enabledOperators parameter for workspace name unique check

- src/core/types/workspace.ts
- src/plugins/workspace/common/constants.ts
- src/plugins/workspace/server/plugin.test.ts
- src/plugins/workspace/server/plugin.ts
- src/plugins/workspace/server/saved_objects/integration_tests/workspace_ui_settings_wrapper.test.ts
- src/plugins/workspace/server/saved_objects/workspace.ts
- src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.test.ts
- src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.ts
When getting ui settings within a workspace, it will combine the workspace ui settings with the global ui settings and workspace ui settings have higher priority if the same setting was defined in both places
When updating ui settings within a workspace, it will update the workspace ui settings, the global ui settings will remain unchanged.
> feat: workspace level ui settings
