src/core/public/index.ts, src/core/public/workspace/workspaces_client.ts, src/core/server/internal_types.ts, src/core/server/server.ts, src/core/server/types.ts, src/core/server/workspaces/index.ts, src/core/server/workspaces/routes/index.ts, src/core/server/workspaces/saved_objects/index.ts, src/core/server/workspaces/saved_objects/workspace.ts, src/core/server/workspaces/types.ts, src/core/server/workspaces/workspaces_client_with_saved_object.ts, src/core/server/workspaces/workspaces_service.ts
=> Workspace service implement

src/core/public/workspace/consts.ts, src/core/public/workspace/workspaces_client.ts, src/core/server/workspaces/routes/index.ts, src/plugins/workspace/public/plugin.ts
=> Use BehaviorObject and optimize code

src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx, src/plugins/workspace/public/components/workspace_creator/workspace_form.tsx
Integrate with workspace create API with workspace create page
=> feat: integrate with workspace create API

src/core/public/fatal_errors/fatal_errors_service.mock.ts, src/core/public/workspace/workspaces_client.ts
=> Add currentWorkspace$

src/plugins/dashboard/public/plugin.tsx, src/plugins/discover/public/plugin.ts, src/plugins/visualize/public/plugin.ts
Register plugin Dashboard/Discover/Visualize with workspace template
=> register plugin with workspace template

src/core/public/chrome/chrome_service.test.ts, src/core/public/chrome/ui/header/collapsible_nav.test.tsx, src/core/public/chrome/ui/header/header.test.tsx, src/plugins/discover/public/plugin.ts, src/plugins/visualize/public/plugin.ts
=> Fix template registration import error

src/plugins/workspace/public/containers/workspace_dropdown_list/workspace_dropdown_list.tsx, src/plugins/workspace/public/mount.tsx
Navigate to workspace create page after create workspace button clicked
=> feat: navigate to workspace create page after button clicked

src/plugins/workspace/common/constants.ts, src/plugins/workspace/public/components/routes.ts, src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx, src/plugins/workspace/public/components/workspace_creator/workspace_form.tsx, src/plugins/workspace/public/components/workspace_overview.tsx, src/plugins/workspace/public/components/workspace_updater/index.tsx, src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
=> Add update workspace page

src/plugins/workspace/public/containers/workspace_dropdown_list/workspace_dropdown_list.tsx
Redirect to overview page after workspace switch
=> Redirect to overview after workspace switch

src/core/public/chrome/ui/header/collapsible_nav.tsx
=> update menu filter logic

src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
Redirect to workspace overview page after workspace created success
=> feat: redirect to workspace overview page after created success

src/plugins/workspace/public/containers/workspace_dropdown_list/workspace_dropdown_list.tsx
Redirect to workspace update page after workspace switch
=> Redirect to workspace update page after workspace switch

src/plugins/workspace/public/components/workspace_app.tsx, src/plugins/workspace/public/hooks.ts
=> remove duplicate EuiPage

src/plugins/workspace/public/containers/workspace_dropdown_list/workspace_dropdown_list.tsx
- remove the clear button beside current workspace
- expand the width of `create workspace` button
=> remove clear button, add the width of create button

src/core/public/saved_objects/saved_objects_service.mock.ts, src/core/server/saved_objects/service/lib/repository.ts, src/core/types/saved_objects.ts
=> Add some logic check when overwrite a saved object

src/plugins/workspace/common/constants.ts, src/plugins/workspace/public/components/routes.ts, src/plugins/workspace/public/components/utils/workspace.ts, src/plugins/workspace/public/components/workspace_list/index.tsx, src/plugins/workspace/public/containers/workspace_dropdown_list/workspace_dropdown_list.tsx
add workspace list and extract switch workspace function
=> add workspace list

src/core/public/injected_metadata/injected_metadata_service.mock.ts, src/core/public/injected_metadata/injected_metadata_service.ts
=> fix: bootstrap error

src/plugins/workspace/opensearch_dashboards.json, src/plugins/workspace/public/components/utils/workspace_column.tsx, src/plugins/workspace/public/plugin.ts
Add workspace column into saved objects table
=> Add workspace column into saved objects table

src/core/public/core_system.ts, src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
=> fix: osd bootstrap error

src/core/utils/default_app_categories.ts, src/plugins/saved_objects_management/public/plugin.ts, src/plugins/workspace/public/plugin.ts
=> feat: do not register app when feature flag is off

src/core/public/chrome/ui/header/collapsible_nav.tsx, src/plugins/workspace/public/plugin.ts
Sort category and non-category nav link according to order in left menu.
Please note that the value of order for **Home** and **Overview** has been changed.
=> Sort category and non-category nav link according to order in left menu

src/core/public/application/types.ts, src/plugins/workspace/public/components/workspace_creator/workspace_form.tsx
1. Remove featureGroup and use management category to indicate admin feature
2. Filter out empty feature categories
=> Feat remove feature group

src/core/public/index.ts, src/core/public/workspace/index.ts, src/core/public/workspace/workspaces_client.ts, src/core/server/workspaces/routes/index.ts, src/core/server/workspaces/types.ts, src/plugins/workspace/public/components/workspace_creator/workspace_form.tsx, src/plugins/workspace/public/components/workspace_creator/workspace_permission_setting_panel.tsx, src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
Add permission control setting to workspace form
=> feat: add permission control section to workspace form

src/core/server/saved_objects/permission_control/acl.test.ts, src/core/server/saved_objects/permission_control/acl.ts, src/core/server/saved_objects/permission_control/client.ts, src/core/server/workspaces/routes/index.ts
- refactor: simplified ACL transformPermissions function
- rename `acl.transformPermissions()` to `acl.toFlatList()`
=> refactor: simplified ACL transformPermission function

src/core/public/utils/index.ts, src/plugins/saved_objects_management/public/lib/get_saved_object_counts.ts, src/plugins/saved_objects_management/public/lib/parse_query.ts, src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx, src/plugins/saved_objects_management/server/routes/scroll_count.ts
=> add workspace filter into saved objects page

src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
=> Show objects without workspace info when no workspaces are provided in find query.

src/plugins/workspace/server/plugin.ts
Call saved objects API with internal user
=> feat: call saved objects with internal user

src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
=> fix: permission check error

src/core/public/chrome/constants.ts, src/core/public/chrome/ui/header/collapsible_nav.tsx, src/core/public/chrome/ui/header/collapsible_nav_header.tsx, src/core/public/core_system.ts, src/core/public/index.ts, src/core/public/saved_objects/saved_objects_client.ts, src/core/public/utils/index.ts, src/core/public/utils/workspace.ts, src/core/public/workspace/index.ts, src/core/public/workspace/workspaces_service.mock.ts, src/core/public/workspace/workspaces_service.ts, src/core/server/index.ts, src/core/server/saved_objects/routes/share.ts, src/core/server/saved_objects/service/lib/repository.ts, src/core/utils/constants.ts, src/core/utils/index.ts, src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx, src/plugins/workspace/public/application.tsx, src/plugins/workspace/public/components/utils/workspace.ts, src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx, src/plugins/workspace/public/plugin.ts, src/plugins/workspace/public/render_workspace_menu.tsx, src/plugins/workspace/public/types.ts, src/plugins/workspace/public/utils.ts, src/plugins/workspace/public/workspace_client.ts, src/plugins/workspace/server/plugin.ts
Refactor workspace dropdown menu from  `CollapsibleNavHeader` to be registered from workspace plugin.
=> refactor: register workspace dropdown menu to left menu

src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
=> fix: navigate to workspace overview after create

src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
=> fix: incorrect permission modes when checking workspace permissions

src/plugins/workspace/public/plugin.ts, src/plugins/workspace/public/utils.test.ts, src/plugins/workspace/server/plugin.ts
Update the feature config of `public` workspace
=> update feature config of public workspace

src/plugins/data/public/index_patterns/index_patterns/redirect_no_index_pattern.tsx
=> fix: redirect error

src/plugins/data_source_management/opensearch_dashboards.json, src/plugins/data_source_management/public/components/page_wrapper/index.ts, src/plugins/data_source_management/public/components/page_wrapper/page_wrapper.tsx, src/plugins/data_source_management/public/management_app/index.ts, src/plugins/data_source_management/public/management_app/mount_management_section.tsx, src/plugins/data_source_management/public/plugin.ts, src/plugins/data_source_management/public/types.ts
=> feat: register data source as application

src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
=> fix: import error in workspace setting

src/plugins/workspace/server/utils.test.ts, src/plugins/workspace/server/utils.ts, src/plugins/workspace/server/workspace_client.ts
Changed workspace id to 6 characters random string
=> Change workspace id to 6 random characters

src/plugins/workspace/common/constants.ts, src/plugins/workspace/public/components/workspace_creator/workspace_form.tsx
filter non-configurable workspace features in workspace configuration page
=> filter non-configurable workspace features in workspace configuration page

src/plugins/advanced_settings/public/management_app/components/page_wrapper/index.ts, src/plugins/advanced_settings/public/management_app/components/page_wrapper/page_wrapper.tsx, src/plugins/advanced_settings/public/management_app/mount_management_section.tsx, src/plugins/advanced_settings/public/plugin.ts
=> feat: register advanced settings under Management category

src/plugins/data/common/index_patterns/index_patterns/index_patterns.ts, src/plugins/data/public/index_patterns/index_patterns/redirect_no_index_pattern.tsx, src/plugins/data/server/saved_objects/index_patterns.ts, src/plugins/index_pattern_management/public/management_app/mount_management_section.tsx, src/plugins/index_pattern_management/public/plugin.ts, src/plugins/opensearch_dashboards_overview/public/components/getting_started/__snapshots__/getting_started.test.tsx.snap, src/plugins/opensearch_dashboards_overview/public/components/getting_started/getting_started.tsx, src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap, src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/relationships.test.tsx.snap, src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/table.test.tsx.snap, src/plugins/saved_objects_management/public/management_section/objects_table/components/relationships.test.tsx, src/plugins/saved_objects_management/public/management_section/objects_table/components/table.test.tsx, src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.tsx, src/plugins/workspace/public/plugin.ts, test/api_integration/apis/saved_objects_management/find.ts, test/api_integration/apis/saved_objects_management/relationships.ts, test/functional/apps/management/_index_pattern_create_delete.js
=> Make index pattern always show under library

src/plugins/workspace/server/plugin.ts, src/plugins/workspace/server/types.ts, src/plugins/workspace/server/workspace_client.ts
=> add workspace name duplication check

src/plugins/workspace/public/components/index.ts, src/plugins/workspace/public/components/workspace_creator/index.tsx, src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx, src/plugins/workspace/public/components/workspace_creator/workspace_form.tsx, src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx, src/plugins/workspace/server/plugin.ts
=> feat: customize management workspace

src/core/public/index.ts, src/core/public/utils/index.ts, src/core/public/utils/workspace.ts, src/core/server/index.ts, src/core/server/saved_objects/constants.ts, src/core/server/saved_objects/index.ts, src/core/server/saved_objects/permission_control/client.ts, src/core/server/saved_objects/routes/share.ts, src/core/utils/constants.ts, src/core/utils/index.ts, src/plugins/workspace/server/workspace_client.ts
=> cleanup: move WORKSPACE_TYPE constant to core/utils/constants

src/plugins/workspace/server/workspace_client.ts
=> fix: type import on WORKSPACE_TYPE

src/core/server/saved_objects/permission_control/client.ts, src/core/server/saved_objects/service/lib/repository.mock.ts, src/core/server/saved_objects/service/lib/repository.ts, src/core/server/saved_objects/service/lib/utils.ts, src/core/server/saved_objects/service/saved_objects_client.ts, src/plugins/workspace/server/index.ts, src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
=> Setup mechanism for register customized query DSL logic

src/core/public/chrome/ui/header/__snapshots__/collapsible_nav.test.tsx.snap, src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap, src/core/public/workspace/workspaces_service.mock.ts, src/core/public/workspace/workspaces_service.ts, src/plugins/workspace/public/plugin.ts, src/plugins/workspace/public/workspace_client.ts
=> refactor: derive currentWorkspace in workspaces_service

src/core/server/index.ts, src/core/types/index.ts, src/core/types/workspace.ts, src/core/utils/constants.ts, src/core/utils/index.ts, src/plugins/workspace/opensearch_dashboards.json, src/plugins/workspace/public/index.ts, src/plugins/workspace/public/plugin.ts, src/plugins/workspace/server/index.ts, src/plugins/workspace/server/plugin.ts, src/plugins/workspace/server/routes/index.ts, src/plugins/workspace/server/saved_objects/index.ts, src/plugins/workspace/server/saved_objects/workspace.ts, src/plugins/workspace/server/types.ts, src/plugins/workspace/server/utils.test.ts, src/plugins/workspace/server/utils.ts, src/plugins/workspace/server/workspace_client.ts, yarn.lock
=> [Feature] Setup workspace skeleton and implement basic CRUD API

src/plugins/home/public/application/components/sample_data_set_cards.js, src/plugins/home/public/application/opensearch_dashboards_services.ts, src/plugins/home/public/application/sample_data_client.js, src/plugins/home/public/plugin.ts, src/plugins/home/server/services/sample_data/data_sets/ecommerce/index.ts, src/plugins/home/server/services/sample_data/data_sets/flights/index.ts, src/plugins/home/server/services/sample_data/data_sets/logs/index.ts, src/plugins/home/server/services/sample_data/data_sets/util.ts, src/plugins/home/server/services/sample_data/lib/sample_dataset_registry_types.ts, src/plugins/home/server/services/sample_data/routes/install.test.ts, src/plugins/home/server/services/sample_data/routes/install.ts, src/plugins/home/server/services/sample_data/routes/list.test.ts, src/plugins/home/server/services/sample_data/routes/list.ts, src/plugins/home/server/services/sample_data/routes/uninstall.test.ts, src/plugins/home/server/services/sample_data/routes/uninstall.ts
Import sample data saved objects to workspace
=> feat: import sample data saved objects to workspace

src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx, src/plugins/workspace/public/components/workspace_creator/workspace_form.tsx, src/plugins/workspace/public/components/workspace_creator/workspace_permission_setting_panel.tsx
Make workspace permission first row deletable for workspace create
=> feat: make workspace permission first row deletable for workspace create

.github/workflows/add-untriaged.yml, .github/workflows/backport.yml, .github/workflows/build_and_test_workflow.yml, .github/workflows/changelog_verifier.yml, .github/workflows/create_doc_issue.yml, .github/workflows/cypress_workflow.yml, .github/workflows/delete_backport_branch.yml, .github/workflows/github-workflow-badger.yml, .github/workflows/links_checker.yml
=> Self host runner

.github/workflows/backport.yml, .github/workflows/build_and_test_workflow.yml, .github/workflows/changelog_verifier.yml, .github/workflows/delete_backport_branch.yml, .github/workflows/links_checker.yml
* feat: add self host runner
* feat: update
* feat: update
* feat: update
* feat: use v4
* feat: update
* Revert "feat: use v4"
This reverts commit fc248672318e322ad8153f872aae62fd2879e71b.
* feat: use auto-scaleable runners
* feat: use sudo
* feat: update
---------
=> [Backport workspace-2.9] Self host runner (#140)

src/plugins/workspace/common/constants.ts, src/plugins/workspace/server/plugin.ts, src/plugins/workspace/server/types.ts, src/plugins/workspace/server/workspace_client.ts
Replace `savedObjectRepository` with `savedObjectClient` for workspace name unique check
=> Replace savedObjectRepository with savedObjectClient

config/opensearch_dashboards.yml, src/plugins/workspace/config.ts, src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
=> refactor: remove dashboard admin implementation

test/functional/apps/management/_opensearch_dashboards_settings.js
=> fix error ftr

src/plugins/discover/public/application/components/top_nav/open_search_panel.tsx, src/plugins/discover_legacy/public/application/components/top_nav/__snapshots__/open_search_panel.test.js.snap
failed tests due to discover 2.0, **should not backport to 2.9**
=> fix failed tests of discover 2.0

src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
=> [Backport workspace-2.9] fix: update unit test snapshot for header

src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
Skip permission validate when no workspaces and permissions attributes
=> feat: skip permission validate when no workspaces and permissions attributes

src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx, src/plugins/workspace/public/workspace_client.ts
=> Cleanup: remove exit workspace logic

src/core/server/saved_objects/service/lib/repository.ts
=> feat: optimize logic when checkConflict and bulkCreate

src/plugins/workspace/public/plugin.ts
=> fix: hide workspace overview and settings when no workspace

src/core/public/application/capabilities/capabilities_service.mock.ts, src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap, src/core/public/workspace/workspaces_service.mock.ts, src/core/public/workspace/workspaces_service.test.ts, src/core/public/workspace/workspaces_service.ts, src/core/server/capabilities/capabilities_service.mock.ts, src/core/server/capabilities/capabilities_service.test.ts, src/core/server/capabilities/capabilities_service.ts, src/core/server/capabilities/integration_tests/capabilities_service.test.ts, src/core/server/capabilities/resolve_capabilities.test.ts, src/core/types/capabilities.ts, src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap, src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap, src/plugins/dashboard/public/application/components/dashboard_top_nav/dashboard_top_nav.tsx, src/plugins/dashboard/public/application/utils/get_nav_actions.tsx, src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap, src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.tsx, src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx, src/plugins/visualize/public/application/utils/get_top_nav_config.tsx, src/plugins/workspace/public/components/delete_workspace_modal/delete_workspace_modal.tsx, src/plugins/workspace/public/plugin.ts, src/plugins/workspace/server/plugin.ts
Implement workspace enabled flag with capabilities service.
=> Workspace enabled flag to capabilities service

src/plugins/home/server/services/sample_data/data_sets/util.ts
Patch #210 changes to workspace branch
=> Patch import sample data to workspace branch

src/core/types/workspace.ts
Fix `yarn osd bootstrap` error by duplicated reserved field
=> fix: remove duplicated reserved field avoid type error

.github/workflows/cypress_workflow.yml
Change default FT Repo branch to `workspace`
=> fix: cypress tests checkout workspace branch

src/plugins/workspace/server/integration_tests/routes.test.ts
=> manual backport #251

CHANGELOG.md, config/opensearch_dashboards.yml, src/core/server/saved_objects/import/types.ts, src/core/server/saved_objects/migrations/core/__snapshots__/build_active_mappings.test.ts.snap, src/core/server/saved_objects/migrations/core/build_active_mappings.test.ts, src/core/server/saved_objects/migrations/core/build_active_mappings.ts, src/core/server/saved_objects/migrations/core/index_migrator.test.ts, src/core/server/saved_objects/migrations/core/migration_context.ts, src/core/server/saved_objects/migrations/opensearch_dashboards/__snapshots__/opensearch_dashboards_migrator.test.ts.snap, src/core/server/saved_objects/migrations/opensearch_dashboards/opensearch_dashboards_migrator.test.ts, src/core/server/saved_objects/migrations/opensearch_dashboards/opensearch_dashboards_migrator.ts, src/core/server/saved_objects/routes/bulk_create.ts, src/core/server/saved_objects/routes/find.ts, src/core/server/saved_objects/routes/resolve_import_errors.ts, src/core/server/saved_objects/saved_objects_service.ts, src/core/server/saved_objects/service/lib/repository.test.js, src/core/server/saved_objects/service/lib/repository.ts, src/core/server/saved_objects/service/lib/search_dsl/query_params.ts, src/core/server/saved_objects/service/saved_objects_client.ts, src/core/server/saved_objects/types.ts, src/plugins/workspace/common/constants.ts, src/plugins/workspace/server/plugin.ts, src/plugins/workspace/server/saved_objects/integration_tests/saved_objects_wrapper_for_check_workspace_conflict.test.ts, src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.test.ts, src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.ts
=> feat: backport pr 5949 to workspace-pr-inte

src/core/server/saved_objects/migrations/core/build_active_mappings.ts, src/core/server/saved_objects/migrations/core/migration_context.ts, src/core/server/saved_objects/migrations/opensearch_dashboards/opensearch_dashboards_migrator.ts, src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.ts
backport official 6012 pr to workspace
=> [Workspace]Following pr for #5949 (#6012)

src/plugins/workspace/server/utils.test.ts, src/plugins/workspace/server/utils.ts
* fix: authInfo destructure
* fix: unit test error
---------
=> fix: authInfo destructure (#7)

src/core/server/saved_objects/service/lib/repository.test.js, src/core/server/saved_objects/service/lib/repository.ts
=> feat: remove useless code

src/plugins/workspace/public/plugin.test.ts
=> fix: unit test

src/plugins/workspace/public/components/workspace_form/utils.test.ts, src/plugins/workspace/public/components/workspace_form/utils.ts
Fix permissions group converting, add related unit tests.
=> Fix group permissions convert

src/plugins/workspace/common/constants.ts, src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx, src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx, src/plugins/workspace/public/components/workspace_form/constants.ts, src/plugins/workspace/public/components/workspace_form/index.ts, src/plugins/workspace/public/components/workspace_form/types.ts, src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts, src/plugins/workspace/public/components/workspace_form/utils.test.ts, src/plugins/workspace/public/components/workspace_form/utils.ts, src/plugins/workspace/public/components/workspace_form/workspace_feature_selector.test.tsx, src/plugins/workspace/public/components/workspace_form/workspace_feature_selector.tsx, src/plugins/workspace/public/components/workspace_form/workspace_form.tsx, src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.test.tsx, src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.tsx, src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_panel.test.tsx, src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_panel.tsx, src/plugins/workspace/public/components/workspace_updater/workspace_updater.test.tsx, src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx, src/plugins/workspace/public/workspace_client.ts, src/plugins/workspace/server/integration_tests/routes.test.ts, src/plugins/workspace/server/routes/index.ts, src/plugins/workspace/server/types.ts, src/plugins/workspace/server/workspace_client.ts
Manual backport https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6378 to pr-integr
=> Manual backport workspace permission tab
